name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Copy project files to EC2 (including .env)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          source: |
            .
            .env
          target: "~/app"

      - name: Run Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ~/app
            if [ ! -f .env ]; then
              echo ".env file not found on EC2. Aborting."
              exit 1
            fi
            docker-compose down
            docker-compose up -d --build
